source 'https://github.com/CocoaPods/Specs.git'

target 'DVACategories', :exclusive => true do
  pod "DVACategories", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DVACategories", :path => "../"

  
end
